
import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/Footer";


const ibmPlexSansHeading = IBM_Plex_Sans({subsets:['latin'],variable:'--font-heading'});

const raleway = Raleway({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Previous starter metadata kept for reference per request.
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "whatisanolive",
  description: "Personal blog covering tech, DSA, and blank-canvas thoughts.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
    lang="en"
    className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", raleway.variable, ibmPlexSansHeading.variable)}
    >
      <body  className="grid-bg min-h-screen flex flex-col">
      <ClerkProvider>

        <Navbar />
        <main className="flex-1">

        {children}
        </main>
        <Footer/>
    </ClerkProvider>
        </body>
    </html>
  );
}
